In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5,6,7,8,9]
arr=np.array(l)

In [3]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(9,)

In [6]:
len(arr)

9

In [9]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr1=arr.copy()

In [21]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# BroadCasting with array
arr1[5:]=200

In [23]:
arr1

array([  1,   2,   3,   4,   5, 200, 200, 200, 200])

In [28]:
arr2=arr1.reshape(3,3)

In [29]:
arr2[1:,2:]

array([[200],
       [200]])

In [31]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [40]:
##Multidimentional array for data analysis like 2D and 3D array


In [34]:
l=np.array([1,2,3,4,5])
l2=np.array([6,7,8,9,10])
l3=np.array([11,12,13,14,15])

In [43]:
#2D array
arr4=np.array([l,l2,l3])

In [44]:
arr4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [50]:
#arange function arange(start,stop,step)
ran=np.arange(1,10,2)

In [51]:
ran

array([1, 3, 5, 7, 9])

In [52]:
ran1=np.arange(1,10)

In [54]:
ran1


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
ran2=100
def check(val):
    if(val<ran2):
        return True
    else:
        return False
for i in arr1:
    print(check(i))

True
True
True
True
True
False
False
False
False


In [62]:
ran3=100
arr1<ran3

array([ True,  True,  True,  True,  True, False, False, False, False])

In [66]:
arr5=np.arange(1,10).reshape(3,3)

In [64]:
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr6=np.array([1,2,3,4,5,6])
arr7=np.array([7,8,9,10,11,12])

In [70]:
arr6*arr7

array([ 7, 16, 27, 40, 55, 72])

In [71]:
np.matmul(arr6,arr7)

217

In [83]:
#Random Funtion
rand=np.random.rand(3,3)

In [84]:
rand

array([[0.47907805, 0.12763583, 0.68706371],
       [0.23431267, 0.8592574 , 0.89568072],
       [0.26652041, 0.47741633, 0.35836469]])

In [97]:
#ones and zeroes in Numpy
recap=np.ones(4,dtype=complex)

In [98]:
recap

array([1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j])

In [99]:
recap1=np.ones(4,dtype=int)

In [100]:
recap1

array([1, 1, 1, 1])

In [102]:
#by default it is present in float
recap2=np.ones(4)
recap2

array([1., 1., 1., 1.])

In [115]:
#Finding min,max,mean,median,variance,standard deviation from a array

In [116]:
rand2=np.random.randn(3,3)

In [117]:
rand2

array([[-2.71872255, -1.24178192, -0.32589126],
       [-0.70461045,  0.04245232, -0.06475016],
       [ 0.42440018,  2.56447951, -1.935586  ]])

In [118]:
np.max(rand2)

2.5644795083111775

In [119]:
np.min(rand2)

-2.7187225529966765

In [120]:
np.mean(rand2)

-0.44000114809082214

In [121]:
np.median(rand2)

-0.32589126259099693

In [122]:
np.std(rand2)

1.4260631575963212

In [123]:
np.var(rand2)

2.03365612945359

In [125]:
# Dot product of an array in numpy


In [149]:
lis=np.arange(0,12).reshape(4,3)

In [150]:
lis

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [158]:
lis1=np.arange(10,22).reshape(3,4)

In [159]:
lis1


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [160]:
dotproduct=np.dot(lis,lis1)

In [161]:
dotproduct

array([[ 50,  53,  56,  59],
       [176, 188, 200, 212],
       [302, 323, 344, 365],
       [428, 458, 488, 518]])

In [163]:
#Matrix multiplication


In [169]:
m=[[1,2,3],[4,5,6]]
m1=[[7,8,9],[10,11,12]]
np.matmul(m,np.transpose(m1))

array([[ 50,  68],
       [122, 167]])

In [174]:
#Identity matrix code is eye(value) function
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])